/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class seatReservation extends javax.swing.JFrame {

    /**
     * Creates new form CinemaMainCodes
     */
    private String movieName;
    private String seatChosen;
    private String costumerName;
    
    public seatReservation() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public seatReservation(String cName, String mname) {
        initComponents();
        movieName = mname;
        costumerName = cName;
        
        this.setLocationRelativeTo(null);
        if(mname.contains("UNDERWATER")){
            moviename.setText(mname);
            ImageIcon ii = new ImageIcon("C:\\Users\\USER\\Desktop\\CinemaReservation\\movie1.jpg");
            Image img=ii.getImage();
            Image rimg=img.getScaledInstance(moviepic.getWidth(), moviepic.getHeight(), java.awt.Image.SCALE_SMOOTH);
            ii=new ImageIcon(rimg);
            moviepic.setIcon(ii);
        }
        else if(mname.contains("FIFTY SHADES")){
            moviename.setText(mname);
            ImageIcon ii = new ImageIcon("C:\\Users\\USER\\Desktop\\CinemaReservation\\movie2.jpg");
            Image img=ii.getImage();
            Image rimg=img.getScaledInstance(moviepic.getWidth(), moviepic.getHeight(), java.awt.Image.SCALE_SMOOTH);
            ii=new ImageIcon(rimg);
            moviepic.setIcon(ii);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seatbtn = new javax.swing.JButton();
        seatbtn1 = new javax.swing.JButton();
        seatbtn2 = new javax.swing.JButton();
        seatbtn3 = new javax.swing.JButton();
        seatbtn4 = new javax.swing.JButton();
        seatbtn5 = new javax.swing.JButton();
        seatbtn6 = new javax.swing.JButton();
        seatbtn7 = new javax.swing.JButton();
        seatbtn8 = new javax.swing.JButton();
        seatbtn9 = new javax.swing.JButton();
        moviepic = new javax.swing.JLabel();
        moviename = new javax.swing.JLabel();
        choosefoodbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seatbtn.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        seatbtn.setForeground(new java.awt.Color(255, 255, 255));
        seatbtn.setText("Unoccupied!");
        seatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatbtnActionPerformed(evt);
            }
        });

        seatbtn1.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        seatbtn1.setForeground(new java.awt.Color(255, 255, 255));
        seatbtn1.setText("Unoccupied!");
        seatbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatbtn1ActionPerformed(evt);
            }
        });

        seatbtn2.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        seatbtn2.setForeground(new java.awt.Color(255, 255, 255));
        seatbtn2.setText("Unoccupied!");
        seatbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatbtn2ActionPerformed(evt);
            }
        });

        seatbtn3.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        seatbtn3.setForeground(new java.awt.Color(255, 255, 255));
        seatbtn3.setText("Unoccupied!");
        seatbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatbtn3ActionPerformed(evt);
            }
        });

        seatbtn4.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        seatbtn4.setForeground(new java.awt.Color(255, 255, 255));
        seatbtn4.setText("Unoccupied!");
        seatbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatbtn4ActionPerformed(evt);
            }
        });

        seatbtn5.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        seatbtn5.setForeground(new java.awt.Color(255, 255, 255));
        seatbtn5.setText("Unoccupied!");
        seatbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatbtn5ActionPerformed(evt);
            }
        });

        seatbtn6.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        seatbtn6.setForeground(new java.awt.Color(255, 255, 255));
        seatbtn6.setText("Unoccupied!");
        seatbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatbtn6ActionPerformed(evt);
            }
        });

        seatbtn7.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        seatbtn7.setForeground(new java.awt.Color(255, 255, 255));
        seatbtn7.setText("Unoccupied!");
        seatbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatbtn7ActionPerformed(evt);
            }
        });

        seatbtn8.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        seatbtn8.setForeground(new java.awt.Color(255, 255, 255));
        seatbtn8.setText("Unoccupied!");
        seatbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatbtn8ActionPerformed(evt);
            }
        });

        seatbtn9.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        seatbtn9.setForeground(new java.awt.Color(255, 255, 255));
        seatbtn9.setText("Unoccupied!");
        seatbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatbtn9ActionPerformed(evt);
            }
        });

        moviename.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N

        choosefoodbtn.setText("CHOOSE FOODS");
        choosefoodbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosefoodbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Movie Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Seat 9");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Seat 7");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Seat 5");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Seat 3");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Seat 1");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Seat 10");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Seat 8");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Seat 6");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Seat 4");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Seat 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seatbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(seatbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seatbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(seatbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seatbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(seatbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seatbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(seatbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seatbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seatbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moviepic, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moviename, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choosefoodbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(seatbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seatbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seatbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seatbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seatbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(moviename, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(choosefoodbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(moviepic, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seatbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatbtnActionPerformed
        String seatStatus = seatbtn.getText();
        seatChosen="Seat 9";
        Color c;
        if(seatStatus.contains("Unoccupied!")){
        seatbtn.setBackground(Color.red);
        seatbtn.setText("Occupied!");
        c = seatbtn.getBackground();
        }
        else if(seatStatus.contains("Occupied!")){
        JOptionPane.showMessageDialog(null, "This seat is occupied!\nPlease choose another seat!",null,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_seatbtnActionPerformed

    private void seatbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatbtn1ActionPerformed
        String seatStatus = seatbtn1.getText();
        seatChosen="Seat 10";
        Color c;
        if(seatStatus.contains("Unoccupied!")){
        seatbtn1.setBackground(Color.red);
        seatbtn1.setText("Occupied!");
        c = seatbtn1.getBackground();
        }
        else if(seatStatus.contains("Occupied!")){
        JOptionPane.showMessageDialog(null, "This seat is occupied!\nPlease choose another seat!",null,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_seatbtn1ActionPerformed

    private void seatbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatbtn2ActionPerformed
        String seatStatus = seatbtn2.getText();
        seatChosen="Seat 7";
        Color c;
        if(seatStatus.contains("Unoccupied!")){
        seatbtn2.setBackground(Color.red);
        seatbtn2.setText("Occupied!");
        c = seatbtn2.getBackground();
        }
        else if(seatStatus.contains("Occupied!")){
        JOptionPane.showMessageDialog(null, "This seat is occupied!\nPlease choose another seat!",null,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_seatbtn2ActionPerformed

    private void seatbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatbtn3ActionPerformed
        String seatStatus = seatbtn3.getText();
        seatChosen="Seat 8";
        Color c;
        if(seatStatus.contains("Unoccupied!")){
        seatbtn3.setBackground(Color.red);
        seatbtn3.setText("Occupied!");
        c = seatbtn3.getBackground();
        }
        else if(seatStatus.contains("Occupied!")){
        JOptionPane.showMessageDialog(null, "This seat is occupied!\nPlease choose another seat!",null,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_seatbtn3ActionPerformed

    private void seatbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatbtn4ActionPerformed
        String seatStatus = seatbtn4.getText();
        seatChosen="Seat 5";
        Color c;
        if(seatStatus.contains("Unoccupied!")){
        seatbtn4.setBackground(Color.red);
        seatbtn4.setText("Occupied!");
        c = seatbtn4.getBackground();
        }
        else if(seatStatus.contains("Occupied!")){
        JOptionPane.showMessageDialog(null, "This seat is occupied!\nPlease choose another seat!",null,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_seatbtn4ActionPerformed

    private void seatbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatbtn5ActionPerformed
        String seatStatus = seatbtn5.getText();
        seatChosen="Seat 6";
        Color c;
        if(seatStatus.contains("Unoccupied!")){
        seatbtn5.setBackground(Color.red);
        seatbtn5.setText("Occupied!");
        c = seatbtn5.getBackground();
        }
        else if(seatStatus.contains("Occupied!")){
        JOptionPane.showMessageDialog(null, "This seat is occupied!\nPlease choose another seat!",null,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_seatbtn5ActionPerformed

    private void seatbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatbtn6ActionPerformed
        String seatStatus = seatbtn6.getText();
        seatChosen="Seat 3";
        Color c;
        if(seatStatus.contains("Unoccupied!")){
        seatbtn6.setBackground(Color.red);
        seatbtn6.setText("Occupied!");
        c = seatbtn6.getBackground();
        }
        else if(seatStatus.contains("Occupied!")){
        JOptionPane.showMessageDialog(null, "This seat is occupied!\nPlease choose another seat!",null,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_seatbtn6ActionPerformed

    private void seatbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatbtn7ActionPerformed
        String seatStatus = seatbtn7.getText();
        seatChosen="Seat 4";
        Color c;
        if(seatStatus.contains("Unoccupied!")){
        seatbtn7.setBackground(Color.red);
        seatbtn7.setText("Occupied!");
        c = seatbtn7.getBackground();
        }
        else if(seatStatus.contains("Occupied!")){
        JOptionPane.showMessageDialog(null, "This seat is occupied!\nPlease choose another seat!",null,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_seatbtn7ActionPerformed

    private void seatbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatbtn8ActionPerformed
        String seatStatus = seatbtn8.getText();
        seatChosen="Seat 1";
        Color c;
        if(seatStatus.contains("Unoccupied!")){
        seatbtn8.setBackground(Color.red);
        seatbtn8.setText("Occupied!");
        c = seatbtn8.getBackground();
        }
        else if(seatStatus.contains("Occupied!")){
        JOptionPane.showMessageDialog(null, "This seat is occupied!\nPlease choose another seat!",null,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_seatbtn8ActionPerformed

    private void seatbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatbtn9ActionPerformed
        String seatStatus = seatbtn9.getText();
        seatChosen="Seat 2";
        Color c;
        if(seatStatus.contains("Unoccupied!")){
        seatbtn9.setBackground(Color.red);
        seatbtn9.setText("Occupied!");
        c = seatbtn9.getBackground();
        }
        else if(seatStatus.contains("Occupied!")){
        JOptionPane.showMessageDialog(null, "This seat is occupied!\nPlease choose another seat!",null,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_seatbtn9ActionPerformed

    private void choosefoodbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosefoodbtnActionPerformed
        setVisible(false);
        new chooseFoods(costumerName,movieName,seatChosen).setVisible(true);
    }//GEN-LAST:event_choosefoodbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seatReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seatReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seatReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seatReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seatReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton choosefoodbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel moviename;
    private javax.swing.JLabel moviepic;
    private javax.swing.JButton seatbtn;
    private javax.swing.JButton seatbtn1;
    private javax.swing.JButton seatbtn2;
    private javax.swing.JButton seatbtn3;
    private javax.swing.JButton seatbtn4;
    private javax.swing.JButton seatbtn5;
    private javax.swing.JButton seatbtn6;
    private javax.swing.JButton seatbtn7;
    private javax.swing.JButton seatbtn8;
    private javax.swing.JButton seatbtn9;
    // End of variables declaration//GEN-END:variables
}
